# Generated by Django 4.1.1 on 2022-09-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('org_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(default=None, max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=10)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.organisation')),
            ],
        ),
    ]
